// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssoumioaizvuqbdceitr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzb3VtaW9haXp2dXFiZGNlaXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDA5MTUsImV4cCI6MjA2Mzk3NjkxNX0.6CJS4ED-nUILdDNN1HrlPRYzh_althMdT34cKYTUJ5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});